[colors.primary]
background = "#191919"
foreground = "#c7c7c7"

[colors.cursor]
cursor = "#ffb472"
text = "#feffff"

[colors.normal]
black = "#616161"
blue = "#a5d5fe"
cyan = "#d0d1fe"
green = "#b4fa72"
magenta = "#ff8ffd"
red = "#ff8272"
white = "#f1f1f1"
yellow = "#fefdc2"

[colors.bright]
black = "#8e8e8e"
blue = "#c1e3fe"
cyan = "#e5e6fe"
green = "#d6fcb9"
magenta = "#ffb1fe"
red = "#ffc4bd"
white = "#feffff"
yellow = "#fefdd5"

