[colors.bright]
black = "0x8e8e8e"
blue = "0xc1e3fe"
cyan = "0xe5e6fe"
green = "0xd6fcb9"
magenta = "0xffb1fe"
red = "0xffc4bd"
white = "0xfeffff"
yellow = "0xfefdd5"

[colors.cursor]
cursor = "0xffb472"
text = "0xfeffff"

[colors.normal]
black = "0x616161"
blue = "0xa5d5fe"
cyan = "0xd0d1fe"
green = "0xb4fa72"
magenta = "0xff8ffd"
red = "0xff8272"
white = "0xf1f1f1"
yellow = "0xfefdc2"

[colors.primary]
background = "0x191919"
foreground = "0xc7c7c7"
