import = [
    "~/.config/alacritty/themes/tspng_dark.toml"
]

[window]
dimensions = { columns = 124, lines = 43 }
decorations = "transparent"
padding = { x = 5, y = 25 }
dynamic_padding = true
opacity = 0.95

[font]
size = 14.0
normal = { family = "Maple Mono" }

[keyboard]
bindings = []

[selection]
save_to_clipboard = true

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "/usr/bin/open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Super"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

