import = [
    ".config/alacritty/themes/tspng_dark.toml"
]

[window]
dimensions = { columns = 124, lines = 43 }
decorations = "Full"

[font]
size = 14.0
normal = { family = "Maple Mono" }

[selection]
save_to_clipboard = true

